import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { existsSync, readFileSync } from "node:fs";
import path from "node:path";
import test from "node:test";
import { fileURLToPath } from "node:url";

const projectDir = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const requestPath = path.join(projectDir, "qwen_voice_request.json");
const audioMetaPath = path.join(projectDir, "audio_meta.json");
const engineMetaPath = path.join(projectDir, "audio_engine_meta.json");
const captionGroupsPath = path.join(projectDir, "caption_groups.json");

function readJson(filePath) {
  return JSON.parse(readFileSync(filePath, "utf8"));
}

function sha256(filePath) {
  return createHash("sha256").update(readFileSync(filePath)).digest("hex");
}

test("voice artifacts are generated by the pinned Qwen3 TTS model", () => {
  assert.ok(existsSync(requestPath), "qwen_voice_request.json must exist");

  const request = readJson(requestPath);
  const meta = readJson(audioMetaPath);

  assert.equal(request.provider, "qwen3-tts");
  assert.equal(request.runtime, "mlx-audio");
  assert.match(request.model, /Qwen3-TTS/);
  assert.equal(meta.tts.provider, request.provider);
  assert.equal(meta.tts.runtime, request.runtime);
  assert.equal(meta.tts.model, request.model);
  assert.equal(meta.tts.voice, request.voice);
  assert.equal(meta.voices.length, request.frames.length);

  for (const voice of meta.voices) {
    const voicePath = path.join(projectDir, voice.path);
    assert.equal(voice.provider, request.provider);
    assert.equal(voice.model, request.model);
    assert.equal(voice.voice, request.voice);
    assert.ok(existsSync(voicePath), `${voice.path} must exist`);
    assert.equal(voice.sha256, sha256(voicePath));
  }
});

test("Qwen phrase timing preserves short readable caption groups", () => {
  const captions = readJson(captionGroupsPath);
  assert.equal(captions.groups.length, 22);
  assert.ok(Math.max(...captions.groups.map((group) => group.text.length)) <= 23);
});

test("Qwen tracks do not leave a long silent tail in any frame", () => {
  const request = readJson(requestPath);
  const meta = readJson(audioMetaPath);
  const voiceByFrame = new Map(meta.voices.map((voice) => [voice.frame, voice]));

  for (const frame of request.frames) {
    const voice = voiceByFrame.get(frame.frame);
    const speechEnd = voice.words.at(-1).end;
    const silentTail = frame.target_duration_s - speechEnd;
    assert.ok(silentTail >= 0.05, `frame ${frame.id} needs a clean audio tail`);
    assert.ok(silentTail <= 0.6, `frame ${frame.id} has ${silentTail.toFixed(3)}s of dead air`);
  }
});

test("audio engine metadata reports the Qwen timeline duration", () => {
  const request = readJson(requestPath);
  const engineMeta = readJson(engineMetaPath);
  const expectedDuration = request.frames.reduce(
    (total, frame) => total + frame.target_duration_s,
    0,
  );

  assert.equal(engineMeta.total_duration_s, expectedDuration);
});
